name       : digikam
version    : 5.5.0
release    : 3
source     :
    - https://download.kde.org/stable/digikam/digikam-5.5.0.tar.xz : df9cbf1b8dbfb9235cebc97e77c02fcb1498c5a905c7fd3b9fb42fd7accc6252
license    :
    - GPL-2.0
    - LGPL-2.1
component  : multimedia.graphics
libsplit   : no
summary    : Advanced digital photo management application
description: |
    digiKam is an advanced digital photo management application for KDE, which makes importing and organizing digital photos a 'snap'.
patterns   :
    - docs :
        - /usr/share/doc
builddeps  :
    - pkgconfig(eigen3)
    - pkgconfig(exiv2)
    - pkgconfig(expat)
    - pkgconfig(glu)
    - pkgconfig(lcms2)
    - pkgconfig(lensfun)
    - pkgconfig(libgphoto2)
    - pkgconfig(libpng)
    - pkgconfig(libtiff-4)
    - pkgconfig(opencv)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5WebKit)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(Qt5XmlPatterns)
    - breeze-devel
    - breeze-icons
    - extra-cmake-modules
    - jasper-devel
    - karchive-devel
    - kconfig-devel
    - kcoreaddons-devel
    - kdoctools-devel
    - kfilemetadata-devel
    - ki18n-devel
    - kiconthemes-devel
    - kio-devel
    - knotifications-devel
    - knotifyconfig-devel
    - kservice-devel
    - kwindowsystem-devel
    - kxmlgui-devel
    - libboost-devel
    - libjpeg-turbo-devel
    - libkipi-devel
    - solid-devel
    - threadweaver-devel
rundeps    :
    - breeze
    - breeze-icons
setup      : |
    %cmake -DENABLE_OPENCV3=ON \
        -DBUILD_TESTING=OFF \
        -DDIGIKAMSC_COMPILE_DOC=OFF .
build      : |
    %make
install    : |
    %make_install
