name       : digikam
version    : 5.8.0
release    : 11
source     :
    - https://cdn.download.kde.org/stable/digikam/digikam-5.8.0.tar.xz : 194a44cc3ca229d501acfba67a38d483d1d64069a85e0491dd28dc2b57091c6e
license    :
    - GPL-2.0
    - LGPL-2.1
component  : multimedia.graphics
libsplit   : no
summary    : Advanced digital photo management application
description: |
    digiKam is an advanced digital photo management application for KDE, which makes importing and organizing digital photos a 'snap'.
patterns   :
    - docs :
        - /usr/share/doc
    - kipi-plugins :
        - /usr/lib64/libKF5kipiplugins*
        - /usr/lib64/qt5/plugins/kipiplugin*
        - /usr/share/applications/kipiplugins.desktop
        - /usr/share/icons/hicolor/*/apps/kipi*
        - /usr/share/kipiplugin*
        - /usr/share/kservices5/kipiplugin*
        - /usr/share/kxmlgui5/kipi/kipiplugin*
        - /usr/share/locale/*/LC_MESSAGES/kipiplugin*
builddeps  :
    - pkgconfig(eigen3)
    - pkgconfig(exiv2)
    - pkgconfig(expat)
    - pkgconfig(glu)
    - pkgconfig(jasper)
    - pkgconfig(lcms2)
    - pkgconfig(lensfun)
    - pkgconfig(libgphoto2)
    - pkgconfig(libpng)
    - pkgconfig(libtiff-4)
    - pkgconfig(libturbojpeg)
    - pkgconfig(opencv)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5WebKit)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(Qt5XmlPatterns)
    - pkgconfig(libxslt)
    - breeze-devel
    - breeze-icons
    - extra-cmake-modules
    - karchive-devel
    - kdoctools-devel
    - kfilemetadata-devel
    - ki18n-devel
    - kiconthemes-devel
    - kio-devel
    - knotifications-devel
    - knotifyconfig-devel
    - kwindowsystem-devel
    - libboost-devel
    - libkipi-devel
    - threadweaver-devel
rundeps    :
    - breeze
    - breeze-icons
    - digikam-kipi-plugins
setup      : |
    pushd core
    %patch -p1 < $pkgfiles/compile-and-link-with-opencv-3.4.0.patch
    popd

    %cmake -DENABLE_OPENCV3=ON \
           -DBUILD_TESTING=OFF .
build      : |
    %make
install    : |
    %make_install

    # Due to SC limitation
    rm -v $installdir/usr/share/metainfo/org.kde.showfoto.appdata.xml
