name       : digikam
version    : 6.4.0
release    : 24
source     :
    - https://cdn.download.kde.org/stable/digikam/6.4.0/digikam-6.4.0-02.tar.xz : 6532c02d51a9861f101092dfde92f8de478b1554d3449bbf3a11e50d32d39460
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : multimedia.graphics
libsplit   : no
summary    : Advanced digital photo management application
description: |
    digiKam is an advanced digital photo management application for KDE, which makes importing and organizing digital photos a 'snap'.
builddeps  :
    - pkgconfig(eigen3)
    - pkgconfig(exiv2)
    - pkgconfig(expat)
    - pkgconfig(glu)
    - pkgconfig(ImageMagick)
    - pkgconfig(jasper)
    - pkgconfig(lcms2)
    - pkgconfig(lensfun)
    - pkgconfig(libavformat)
    - pkgconfig(libgphoto2)
    - pkgconfig(libpng)
    - pkgconfig(libtiff-4)
    - pkgconfig(libturbojpeg)
    - pkgconfig(opencv)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5WebEngine)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(Qt5XmlPatterns)
    - pkgconfig(libxslt)
    - akonadi-devel
    - akonadi-contacts-devel
    - breeze-devel
    - breeze-icons
    - extra-cmake-modules
    - kcalendarcore-devel
    - kcontacts-devel
    - kfilemetadata-devel
    - ki18n-devel
    - kiconthemes-devel
    - kio-devel
    - knotifications-devel
    - knotifyconfig-devel
    - kwindowsystem-devel
    - libboost-devel
    - libkipi-devel
    - libksane-devel
    - libkvkontakte-devel
    - marble-devel
    - threadweaver-devel
rundeps    :
    - breeze
    - breeze-icons
setup      : |
    %cmake_ninja \
        -DBUILD_TESTING=OFF \
        -DENABLE_KFILEMETADATASUPPORT=ON \
        -DENABLE_AKONADICONTACTSUPPORT=ON \
        -DENABLE_APPSTYLES=ON \
        -DENABLE_QWEBENGINE=ON \
        -DENABLE_OPENCV3=ON \
        -DOpenGL_GL_PREFERENCE=GLVND
build      : |
    %ninja_build
install    : |
    %ninja_install

    # Due to SC limitation
    rm -v $installdir/usr/share/metainfo/org.kde.showfoto.appdata.xml
